## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,2,Naftalan,AZ,85.42,scattered clouds,40.5067,46.8250,Gashalti Health Hotel - Naftalan
1,5,Saint George,US,82.80,clear sky,37.1041,-113.5841,Best Western Plus Abbey Inn
2,6,Nouadhibou,MR,75.18,clear sky,20.9310,-17.0347,El Medina
3,10,Padang,ID,77.05,overcast clouds,-0.9492,100.3543,Mercure Padang
4,29,Itarema,BR,83.53,broken clouds,-2.9248,-39.9167,"Sea Lounge! Bar, Club & Restaurant"

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info )
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig
# 4b. Display the figure

Figure(layout=FigureLayout(height='420px'))

In [6]:
us_locations_df = vacation_df[vacation_df["Country"] == 'US']
us_locations_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,5,Saint George,US,82.80,clear sky,37.1041,-113.5841,Best Western Plus Abbey Inn
5,30,Brigantine,US,75.20,clear sky,39.4101,-74.3646,Legacy Vacation Resorts - Brigantine Beach
11,43,San Patricio,US,85.91,clear sky,28.0170,-97.5169,"Motel 6 Sinton, TX"
20,64,Filadelfia,US,75.22,few clouds,39.9523,-75.1638,"The Ritz-Carlton, Philadelphia"
26,78,Callaway,US,87.91,clear sky,30.1530,-85.5699,Holiday Inn Express & Suites Panama City-Tynda...
45,139,Iberia,US,86.05,scattered clouds,29.9502,-91.7507,back to back rv park
90,270,Kahului,US,75.85,clear sky,20.8947,-156.4700,Maui Seaside Hotel
92,279,Las Cruces,US,87.91,clear sky,32.3123,-106.7783,SpringHill Suites by Marriott Las Cruces
98,288,Mayo,US,76.33,clear sky,38.8876,-76.5119,Resorts Resource Group International
125,385,Taos,US,76.21,clear sky,36.4072,-105.5731,El Monte Sagrado
148,454,Eufaula,US,82.44,thunderstorm,31.8913,-85.1455,Days Inn by Wyndham Eufaula AL
159,479,Cape Canaveral,US,87.08,clear sky,28.4058,-80.6048,Residence Inn by Marriott Cape Canaveral Cocoa...
166,493,Havelock,US,76.98,overcast clouds,34.8791,-76.9013,Sherwood Motel
176,520,Key West,US,89.60,clear sky,24.5557,-81.7826,Fairfield Inn & Suites by Marriott Key West
188,544,Houma,US,86.00,overcast clouds,29.5958,-90.7195,Courtyard by Marriott Houma
201,582,Half Moon Bay,US,75.88,mist,37.4636,-122.4286,"The Ritz-Carlton, Half Moon Bay"
211,609,Nanakuli,US,75.15,clear sky,21.3906,-158.1547,Camp PÄlehua
226,644,Hamilton,US,75.88,clear sky,39.1834,-84.5333,Six Acres Bed & Breakfast

In [11]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = us_locations_df.loc[5]
vacation_end = us_locations_df.loc[5]
vacation_stop1 = us_locations_df.loc[20]
vacation_stop2 = us_locations_df.loc[98] 
vacation_stop3 = us_locations_df.loc[148]

In [8]:
vacation_start

City_ID                                                        30
City                                                   Brigantine
Country                                                        US
Max Temp                                                     75.2
Current Description                                     clear sky
Lat                                                       39.4101
Lng                                                      -74.3646
Hotel Name             Legacy Vacation Resorts - Brigantine Beach
Name: 5, dtype: object

In [14]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = (vacation_start['Lat'],vacation_start['Lng'])
end = (vacation_end['Lat'],vacation_end['Lng'])
stop1 = (vacation_stop1['Lat'],vacation_stop1['Lng'])
stop2 = (vacation_stop2['Lat'],vacation_stop2['Lng'])
stop3 = (vacation_stop3['Lat'],vacation_stop3['Lng'])

In [23]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,

us_locs_tuples = (start, stop1, stop2, stop3)
fig = gmaps.figure(center=(39.0, -75.0), zoom_level=3)
marker_layer = gmaps.marker_layer(us_locs_tuples)
full_itinerary = gmaps.directions_layer(start,end, waypoints=[stop1,stop2,stop3,end],travel_mode="DRIVING")
fig.add_layer(marker_layer)
fig.add_layer(full_itinerary)


# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3,vacation_end],ignore_index=True)
print(itinerary_df)

0                                             30
1                                     Brigantine
2                                             US
3                                           75.2
4                                      clear sky
5                                        39.4101
6                                       -74.3646
7     Legacy Vacation Resorts - Brigantine Beach
8                                             64
9                                     Filadelfia
10                                            US
11                                         75.22
12                                    few clouds
13                                       39.9523
14                                      -75.1638
15                The Ritz-Carlton, Philadelphia
16                                           288
17                                          Mayo
18                                            US
19                                         76.33
20                                     clear sky
21                                       38.8876
22                                      -76.5119
23          Resorts Resource Group International
24                                           454
25                                       Eufaula
26                                            US
27                                         82.44
28                                  thunderstorm
29                                       31.8913
30                                      -85.1455
31                Days Inn by Wyndham Eufaula AL
32                                            30
33                                    Brigantine
34                                            US
35                                          75.2
36                                     clear sky
37                                       39.4101
38                                      -74.3646
39    Legacy Vacation Resorts - Brigantine Beach
dtype: object

In [19]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""
# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

AttributeError: 'Series' object has no attribute 'iterrows'

In [10]:
# 11a. Add a marker layer for each city to the map.

# 11b. Display the figure